hetic_solidarite_sida_database:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=symfony
    volumes:
        - "./my.cnf:/etc/my.cnf"
