services:
    app.controller_listener:
        class: PeopleBundle\Middleware\UserProviderMiddleware
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    CurrentUser:
        class: PeopleBundle\Repository\CurrentUser
        arguments: [ "@ZoneHasChiefRepository", "@PoleHasChiefRepository" ]

    PeopleRepository:
        class: PeopleBundle\Repository\PeopleRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PeopleBundle\Entity\People

    BeneboxGuzzleClient:
        class: GuzzleHttp\Client

    BeneboxClient:
        class: PeopleBundle\Client\BeneboxClient
        arguments: [ "@BeneboxGuzzleClient" ]

    AuthenticationService:
        class: PeopleBundle\Service\AuthenticationService
        arguments: [ "@BeneboxClient", "@PeopleRepository" ]
