services:
    PeopleRepository:
        class: PeopleBundle\Repository\PeopleRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PeopleBundle\Entity\People

    BeneboxGuzzleClient:
        class: GuzzleHttp\Client

    BeneboxClient:
        class: PeopleBundle\Client\BeneboxClient
        arguments: [ "@BeneboxGuzzleClient" ]

    AuthenticationService:
        class: PeopleBundle\Service\AuthenticationService
        arguments: [ "@BeneboxClient", "@PeopleRepository" ]
