services:
    ZoneRepository:
        class: EventBundle\Repository\ZoneRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - EventBundle\Entity\Zone

    ZoneHasChiefRepository:
        class: EventBundle\Repository\ZoneRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - EventBundle\Entity\ZoneHasChief

    TeamRepository:
        class: EventBundle\Repository\TeamRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - EventBundle\Entity\Team

    TeamHasChiefRepository:
        class: EventBundle\Repository\TeamRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - EventBundle\Entity\TeamHasChief

    PoleRepository:
        class: EventBundle\Repository\PoleRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
        - EventBundle\Entity\Pole

    PoleHasChiefRepository:
        class: EventBundle\Repository\PoleRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - EventBundle\Entity\PoleHasChief

    SubteamRepository:
        class: EventBundle\Repository\SubteamRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
        - EventBundle\Entity\Subteam

    SubteamHasChiefRepository:
        class: EventBundle\Repository\SubteamHasChiefRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - EventBundle\Entity\SubteamHasChief

    SubteamHasAdjointRepository:
        class: EventBundle\Repository\SubteamHasAdjointRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - EventBundle\Entity\SubteamHasAdjoint
